---
AWSTemplateFormatVersion: 2010-09-09

Description: WordPress on AWS - Creates EFS file system

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: File System Parameters
      Parameters:
        - EfsEncrpytedBoolean
        - EfsCmk
        - EfsSecurityGroup
        - DataSubnet0
        - DataSubnet1
        - DataSubnet2
    ParameterLabels:
      EfsEncrpytedBoolean:
        default: Encrypted EFS File system
      EfsCmk:
        default: AWS KMS Customer Master Key (CMK) to encrypt EFS
      EfsSecurityGroup:
        default: EFS Security Group
      DataSubnet0:
        default: Data Subnet for AZ 0
      DataSubnet1:
        default: Data Subnet for AZ 1
      DataSubnet2:
        default: Data Subnet for AZ 2

Parameters:

  EfsEncrpytedBoolean:
    AllowedValues:
      - True
      - False
    Default: False
    Description: Create an encrypted Amazon EFS file system.
    Type: String
  EfsCmk:
    Description: An existing AWS KMS CMK ARN
    Type: String
  EfsSecurityGroup:
    Description: Select the EFS security group.
    Type: AWS::EC2::SecurityGroup::Id
  DataSubnet0:
    Description: Select an existing data subnet for AZ 0.
    Type: AWS::EC2::Subnet::Id
  DataSubnet1:
    Description: Select an existing data subnet for AZ 1.
    Type: AWS::EC2::Subnet::Id
  DataSubnet2:
    Description: Select an existing data subnet for AZ 2.
    Type: AWS::EC2::Subnet::Id

Conditions:

  UseAWS-ManagedCMK:
    !Equals ['', !Ref EfsCmk]
  MoreThan2AZ:
    !Or [
      !Equals [ !Ref 'AWS::Region', us-east-1 ],
      !Equals [ !Ref 'AWS::Region', us-east-2 ],
      !Equals [ !Ref 'AWS::Region', us-west-2 ]
    ]

Resources:

  ElasticFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: !Ref EfsEncrpytedBoolean
      KmsKeyId:
        !If [ UseAWS-ManagedCMK, !Ref 'AWS::NoValue', !Ref EfsCmk ]
      FileSystemTags:
        - Key: Name
          Value: !Join [ '', [ 'WordPress / ', !Ref 'AWS::StackName' ] ]
      PerformanceMode: generalPurpose
  ElasticFileSystemMountTarget0:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SecurityGroups:
      - !Ref EfsSecurityGroup
      SubnetId: !Ref DataSubnet0
  ElasticFileSystemMountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SecurityGroups:
      - !Ref EfsSecurityGroup
      SubnetId: !Ref DataSubnet1
  ElasticFileSystemMountTarget2:
    Condition: MoreThan2AZ
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref ElasticFileSystem
      SecurityGroups:
      - !Ref EfsSecurityGroup
      SubnetId: !Ref DataSubnet2

Outputs:
  ElasticFileSystem:
    Value: !Ref ElasticFileSystem
  ElasticFileSystemDnsName:
    Description: DNS name for the EFS file system.
    Value: !Join [ '.', [ !Ref ElasticFileSystem, 'efs', !Ref 'AWS::Region', 'amazonaws', 'com' ] ]
  ElasticFileSystemMountCommand:
    Description: Mount command for mounting the EFS file system.
    Value: !Join [ '', [ 'sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ', !Join [ '.', [ !Ref ElasticFileSystem, 'efs', !Ref 'AWS::Region', 'amazonaws', 'com:/ /var/www/wordpress' ] ] ] ]
